package hibernate.modelo;
// Generated 26/06/2013 07:16:12 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,catalog="itic9a"
)
public class Alumno  implements java.io.Serializable {


     private Integer idAlumno;
     private Grupo grupo;
     private String nombre;
     private String matricula;

    public Alumno() {
    }

    public Alumno(Grupo grupo, String nombre, String matricula) {
       this.grupo = grupo;
       this.nombre = nombre;
       this.matricula = matricula;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdAlumno", unique=true, nullable=false)
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdGrupo")
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="matricula")
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }




}


